---
title: "STA302tut1"
author: "Hechen Zhang"
format: pdf
editor: visual
---

```{r}
#### Workspace setup ####
 install.packages("tidyverse")
 install.packages("janitor")

library(tidyverse)
library(janitor)
```

```{r}
simulated_data <-
    tibble(
        # Use 1 through to 338 to represent each seat
        "seat" = 1:338,
        # Randomly pick an option, with replacement, 338 times
        "Party" = sample(
            x = c("Liberal", "Conservative", "Bloc Québécois", "New Democratic", "Green", "Others"),
            size = 338,
            replace = TRUE
        )
    )

simulated_data
```

```{r}
#### Read in the data ####
raw_elections_data <-
  read_csv(
    file = 
      "https://www.elections.ca/res/rep/off/ovr2021app/53/data_donnees/table_tableau11.csv",
    show_col_types = FALSE,
  )

# We have read the data from the website. We may like to save
# it in case something happens or they move it.
write_csv(
  x = raw_elections_data,
  file = "canadian_voting.csv"
)

head(raw_elections_data)
tail(raw_elections_data)
```

```{r}
#### Basic cleaning ####
raw_elections_data <-
  read_csv(
    file = "canadian_voting.csv",
    show_col_types = FALSE
  )

# Make the names easier to type
cleaned_elections_data <-
  clean_names(raw_elections_data)

# Have a look at the first six rows
head(cleaned_elections_data)
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  select(
    electoral_district_name_nom_de_circonscription,
    elected_candidate_candidat_elu
  )

cleaned_elections_data <-
  cleaned_elections_data |>
  rename(
    district_name = electoral_district_name_nom_de_circonscription,
    elected_candidate = elected_candidate_candidat_elu
  )

head(cleaned_elections_data)
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  separate(
    col = elected_candidate,
    into = c("Other", "party"),
    sep = "/"
  ) |>
  select(-Other)
```

```{r}
cleaned_elections_data$party |>
  unique()
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  mutate(
    party =
      case_match(
        party,
        "Libéral" ~ "Liberal",
        "Conservateur" ~ "Conservative",
        "Bloc Québécois" ~ "Bloc Quebecois",
        "NPD-Nouveau Parti démocratique" ~ "New Democratic Party,",
        "Parti Vert" ~ "Green Party"
      )
  )
```
